global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Cargar reglas de alertas
rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  # Prometheus se scrapea a sí mismo
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter de esta misma máquina
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
